//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamborghini.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConfig
    {
        public int ConID { get; set; }
        public string Paint { get; set; }
        public string Rims { get; set; }
        public string BrakeAndCaliper { get; set; }
        public string EngineArea { get; set; }
        public string TopView { get; set; }
        public byte[] PaintJob { get; set; }
    }
}
