//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamborghini.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomConfig
    {
        public int ConfID { get; set; }
        public string Cpaint { get; set; }
        public string Crims { get; set; }
        public string CbrakeAndcaliper { get; set; }
        public string CengineArea { get; set; }
        public string CtopView { get; set; }
        public byte[] CarImage { get; set; }
    }
}
